config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehiculo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),


]

vehiculo/urls.py
from django.urls import path
from . import views

app_name = 'vehiculo'

urlpatterns = [
    path('', views.index, name='index'),
    path('vehiculo/add', views.vehiculo_add, name='vehiculo_add'),
    path('list/', views.vehiculo_list, name='vehiculo_list'),
    path('signup/', views.signup, name='signup'),

]

vehiculo/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver


# Modelo de la tabla Vehiculo en la base de datos
class Vehiculo(models.Model):
    MARCAS = [
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    ]
    CATEGORIAS = [
        ('Particular', 'Particular'),
        ('Transporte', 'Transporte'),
        ('Carga', 'Carga'),
    ]
    marca = models.CharField(max_length=20, choices=MARCAS, default='Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, choices=CATEGORIAS, default='Particular')
    precio = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    # Método para retornar el nombre del vehículo
    def __str__(self):
        return self.marca + ' ' + self.modelo

    # Añadir permisos
    class Meta:
        permissions = [
            ("visualizar_catalogo", "Puede visualizar el catálogo de vehículos"),
            ("agregar_vehiculo", "Puede agregar un nuevo vehículo"),
        ]
    
    # Método para retornar la categoría del vehículo
    def precio_categoria(self):
        if self.precio <= 10000:
            return 'Bajo'
        elif self.precio <= 30000:
            return 'Medio'
        else:
            return 'Alto'

# Signal para añadir el permiso 'visualizar_catalogo' a los nuevos usuarios
@receiver(post_save, sender=User)
def add_permiso_visualizar(sender, instance, created, **kwargs):
    if created:
        permiso = Permission.objects.get(codename='visualizar_catalogo')
        instance.user_permissions.add(permiso)

vehiculo/forms.py
from django import forms
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']

vehiculo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .forms import VehiculoForm
from .models import Vehiculo


# Create your views here.

# Vista de la página principal de la aplicación
def index(request):
    return render(request, 'vehiculo/index.html')


# Vista para agregar un nuevo vehículo
@login_required
@permission_required('vehiculo.agregar_vehiculo', login_url='/accounts/login/')
def vehiculo_add(request):
    if request.method == "POST":
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vehiculo:index')
    else:
        form = VehiculoForm()

    return render(request, 'vehiculo/vehiculo_add.html', {'form': form})


# Vista para listar los vehículos
@login_required
@permission_required('vehiculo.visualizar_catalogo')
def vehiculo_list(request):
    vehiculos = Vehiculo.objects.all()
    return render(request, 'vehiculo/vehiculo_list.html', {'vehiculos': vehiculos})


# Vista para registro de usuario
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('vehiculo:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Metadata -->
    <meta charset="UTF-8">
    <meta name="author" content="JIgnacioGO">
    <meta name="description" content="Catalogo de vehiculos">
    <meta name="keywords" content="vehiculos, Catalogo">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Titulo -->
    <title>Proyecto Vehículos Django</title>
    <!--CSS  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand">Vehiculos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'vehiculo:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        {% if perms.vehiculo.agregar_vehiculo %}
                        <a class="nav-link" href="{% url 'vehiculo:vehiculo_add' %}">Agregar</a>
                        {% endif %}
                    </li>
                    <li class="nav-item"></li>
                    <li class="nav-item">
                        {% if perms.vehiculo.visualizar_catalogo %}
                        <a class="nav-link" href="{% url 'vehiculo:vehiculo_list' %}">Listar</a>
                        {% endif %}
                    </li>
                    <li class="nav-item"></li>

                </ul>
                {% if request.user.is_authenticated %}
                <span class="navbar-text ms-auto">
                    Bienvenido
                    {% if request.user.is_staff %}
                    <a href="{% url 'admin:index' %}">{{ user.username }}</a>
                    {% else %}
                    {{ user.username }}
                    {% endif %}
                    | <a href="{% url 'logout' %}">Salir</a>
                </span>
                {% else %}
                <span class="navbar-text ms-auto">
                    <a href="{% url 'login' %}">Acceder</a> |
                    <a href="{% url 'vehiculo:signup' %}">Registrarse</a>
                </span>
                {% endif %}

            </div>
        </div>
    </nav>



    {% block content %}{% endblock %}
</body>

</html>

vehiculo/templates/vehiculo/index.html
{% extends "base.html" %}

{% block content %}

<!--  Jumbotron -->
<div class=" jumbotron-fluid bg-transparente text-light p-5">
    <div class="container-fluid">
        <h1 class="display-4">Catálogo de Vehículos</h1>
        <p class="lead">Descubre una variedad de vehículos a tu disposición.</p>
    </div>
</div>

{% endblock %}

vehiculo/templates/vehiculo/vehiculo_add.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--  Jumbotron -->
<div class=" jumbotron-fluid bg-transparente text-light p-5">
    <div class="container-fluid">
        <h1 class="display-4">Agregar Vehículos</h1>
    </div>
</div>


<section class="container">
    <div class="container-fluid bg-transparente-radial rounded-3 container-vehiculo-list">
        <div class="mx-5 text-light">
            <form method="post" class="d-flex flex-column align-items-center">
                {% csrf_token %}
                <div class="row d-flex flex-wrap justify-content-around">
                    <div class="col-12 col-md-6 mt-5 mb-3">
                        {{ form.marca|as_crispy_field }}
                        {{ form.modelo|as_crispy_field }}
                        {{ form.serial_carroceria|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6 mt-5 mb-3">
                        {{ form.serial_motor|as_crispy_field }}
                        {{ form.categoria|as_crispy_field }}
                        {{ form.precio|as_crispy_field }}
                    </div>
                </div>
                <button class="btn btn-outline-light mt-3" type="submit">Guardar</button>
            </form>
        </div>
    </div>
</section>



{% endblock %}

vehiculo/templates/vehiculo/vehiculo_list.html
{% extends "base.html" %}

{% block content %}

<!--  Jumbotron -->
<div class=" jumbotron-fluid bg-transparente text-light p-5">
    <div class="container-fluid">
        <h1 class="display-4">Listado de Vehículos</h1>
    </div>
</div>

<section class="container">
    <div class="container-fluid p-5 bg-transparente-radial rounded-3 container-vehiculo-list">
        <div class="table-responsive">
            <table class="table table-hover text-light">
                <thead>
                    <tr>
                        <th scope="col">Marca</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Serial Carroceria</th>
                        <th scope="col">Serial Motor</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Condición de Precio</th>
                    </tr>
                </thead>
                <tbody>
                    {% for vehiculo in vehiculos %}
                    <tr>
                        <td>{{ vehiculo.marca }}</td>
                        <td>{{ vehiculo.modelo }}</td>
                        <td>{{ vehiculo.serial_carroceria | upper }}</td>
                        <td>{{ vehiculo.serial_motor | upper }}</td>
                        <td>{{ vehiculo.categoria }}</td>
                        <td>{{ vehiculo.precio }}</td>
                        <td>{{ vehiculo.precio_categoria }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</section>

{% endblock %}